In [1]:
import numpy as np
zeros_arr = np.zeros ((2 ,3) )
print (" A zeros array is \n", zeros_arr ,"with dimensions ", zeros_arr.shape , "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions  (2, 3) 



In [2]:
import numpy as np

arr1d = np . array ([0 , 1 , 2 , 3 , 4 , 5])
arr2d = np . array ([[0 , 1 , 2] , [3 , 4 , 5] , [6 , 7 , 8]])
arr3d = np . array ([[[0 , 1] , [2 , 3]] , [[4 , 5] , [6 , 7]] , [[8 ,9] , [10 , 11]]])

print (" Basic :", arr1d [1:4] , arr2d [1:3 , 0:2] , arr3d [1:2 , 0:2 ,
1:2])


print (" Step :", arr1d [1:5:2] , arr2d [::2 , 1::2] , arr3d [::2 ,
::2 , 1::2])


 Basic : [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
 Step : [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


Problem 1: Array Creation

In [3]:
import numpy as np
empty_arr = np.empty ((2,2))
print(empty_arr)

[[4.88972352e-310 0.00000000e+000]
 [2.96439388e-323 3.45845952e-323]]


In [4]:
import numpy as np
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
shape = (3,2)
dtype = np.int32
fill_value = 7
filled_array = np.full(shape, fill_value, dtype=dtype)
print(filled_array)

[[7 7]
 [7 7]
 [7 7]]


In [6]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
zeros_array = np.zeros_like(original_array)
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [8]:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


Problem 2: Array Multiplication

In [9]:
import numpy as np
array_range = np.arange(10,50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)


0.5148874843876547


In [13]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(min_value, max_value)

0.020225870539055446 0.9957512285213882


In [14]:
zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [16]:
shape = (5,5)
array_2d = np.ones(shape, dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [17]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3: Array Operation


In [18]:
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_xy = x + y
add_vw = v + w

sub_xy = x - y
sub_vw = v - w

mult_xy = x * y
mult_vw = v * w

sq_x = x**2
sq_y = y**2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)



Problem 4: Matrix Operation


In [19]:
import numpy as np

A = np.array([[3,4], [7,8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [20]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [21]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
BT_AT = np.dot(B_T, A_T)

print(AB_T)
print(BT_AT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [22]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[ 2.  1. -2.]


In [23]:

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])


x = np.linalg.solve(A, b)

print(x)

[ 2.  1. -2.]


EXPERIMENT

In [ ]:
import numpy as np
import time

# Define sizes
list_size = 1_000_000
matrix_size = 1000

# Create lists and arrays
list1 = [i for i in range(list_size)]
list2 = [i for i in range(list_size)]

array1 = np.array(list1)
array2 = np.array(list2)

# 1. Element-wise Addition
# Python lists
start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(list_size)]
list_add_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_array_add = array1 + array2
array_add_time = time.time() - start_time

print(f"Element-wise Addition: Python Lists = {list_add_time:.6f}s, NumPy Arrays = {array_add_time:.6f}s")

# 2. Element-wise Multiplication
# Python lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(list_size)]
list_mul_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_array_mul = array1 * array2
array_mul_time = time.time() - start_time

print(f"Element-wise Multiplication: Python Lists = {list_mul_time:.6f}s, NumPy Arrays = {array_mul_time:.6f}s")

# 3. Dot Product
# Python lists
start_time = time.time()
result_list_dot = sum(list1[i] * list2[i] for i in range(list_size))
list_dot_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_array_dot = np.dot(array1, array2)
array_dot_time = time.time() - start_time

print(f"Dot Product: Python Lists = {list_dot_time:.6f}s, NumPy Arrays = {array_dot_time:.6f}s")


matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

# Python lists
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
matrix_mul_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_np_matrix = np.dot(np_matrix1, np_matrix2)
np_matrix_mul_time = time.time() - start_time

print(f"Matrix Multiplication: Python Lists = {matrix_mul_time:.6f}s, NumPy Arrays = {np_matrix_mul_time:.6f}s")

Element-wise Addition: Python Lists = 0.162939s, NumPy Arrays = 0.003855s
Element-wise Multiplication: Python Lists = 0.177233s, NumPy Arrays = 0.004251s
Dot Product: Python Lists = 0.164470s, NumPy Arrays = 0.001741s
